name: wsl-ssh-agent release

on:
  create:
    tags:
    - "v*.*.*"

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: binutils-mingw-w64-x86-64
        version: 1.0
 
    - name: Ubuntu version
      run: lsb_release -a

    - name: Get latest CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latest
        ninjaVersion: latest

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build - win64
      env:
        MSYSTEM_NAME: win64
      run: |
        cmake -G Ninja -B build_win64
        cmake --build build_win64 --target release

    - name: Sign release artifacts
      # After lunar this could be replaced with "apt install minisign"
      uses: thomasdesr/minisign-action@v1
      with:
        args: -Sm wsl-ssh-agent.zip
        minisign_key: ${{ secrets.minisign_key }}
        password: ${{ secrets.minisign_password }}

    - name: List results
      run: ls -lah wsl-ssh-*

    - name: Upload release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
        files: |
          wsl-ssh-agent.json
          wsl-ssh-agent.zip
          wsl-ssh-agent.zip.minisig
